# 🚀 Run this notebook in Google Colab!

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/your-repo/numpy-tutorial.ipynb)

---

# Introduction to NumPy
## A Beginner's Guide to Scientific Computing with Python

**Duration:** 50 minutes  


---

## What You'll Learn Today:
1. What is NumPy and why do we need it?
2. Creating and understanding NumPy arrays
3. Basic array operations and indexing
4. Mathematical operations with arrays
5. Practical applications and examples

---

**Prerequisites:** Basic Python knowledge (lists, loops, functions)

## 1. What is NumPy? (5 minutes)

**NumPy** stands for **Numerical Python**. It's a fundamental library for scientific computing in Python.

### Why do we need NumPy?

**Problem with Python lists:**
- Slow for large datasets
- Limited mathematical operations
- Memory inefficient

**NumPy advantages:**
- ⚡ **Speed**: Operations are 10-100x faster than pure Python
- 🧮 **Mathematical functions**: Built-in mathematical operations
- 📊 **Memory efficient**: Stores data more compactly
- 🔗 **Integration**: Works seamlessly with other scientific libraries

In [1]:
# Google Colab Setup (NumPy is pre-installed, but let's verify)
import sys
print("Python version:", sys.version)

# Import required libraries
import numpy as np
import time
import warnings
warnings.filterwarnings('ignore')  # Suppress warnings for cleaner output

# Colab-specific: Enhanced display settings
from IPython.display import display, HTML
display(HTML("<h3>✅ All libraries imported successfully!</h3>"))

print(f"📦 NumPy version: {np.__version__}")
print(f"🖥️  Running on: {'Google Colab' if 'google.colab' in sys.modules else 'Local Environment'}")

Python version: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]


📦 NumPy version: 1.26.4
🖥️  Running on: Local Environment


### ⚡ Performance Showdown: Python vs NumPy

Let's see the **real power** of NumPy by measuring execution time!

In [ ]:
import timeit
import matplotlib.pyplot as plt

# Create test data of different sizes
size =  1000000
python_times = []
numpy_times = []

print("🏁 Performance Race: Python for-loop vs NumPy")
print("=" * 60)

print(f"\n📊 Testing with {size:,} elements...")

# Create test data
python_list = list(range(size))
numpy_array = np.array(python_list)

# Method 1: Python for-loop (the old way)
def python_sum():
    total = 0
    for num in python_list:
        total += num
    return total

# Method 2: NumPy sum (the NumPy way)
def numpy_sum():
    return np.sum(numpy_array)

# Time both methods using timeit (more accurate than time.time())
python_time = timeit.timeit(python_sum, number=10) / 10  # Average of 10 runs
numpy_time = timeit.timeit(numpy_sum, number=10) / 10    # Average of 10 runs

python_times.append(python_time)
numpy_times.append(numpy_time)

# Calculate speedup
speedup = python_time / numpy_time

print(f"   🐍 Python for-loop: {python_time:.6f} seconds")
print(f"   ⚡ NumPy np.sum():   {numpy_time:.6f} seconds")
print(f"   🚀 NumPy is {speedup:.1f}x FASTER!")

# Verify both methods give same result
assert python_sum() == numpy_sum(), "Results don't match!"


🏁 Performance Race: Python for-loop vs NumPy

📊 Testing with 1,000,000 elements...
   🐍 Python for-loop: 0.025803 seconds
   ⚡ NumPy np.sum():   0.000383 seconds
   🚀 NumPy is 67.4x FASTER!
   🐍 Python for-loop: 0.025803 seconds
   ⚡ NumPy np.sum():   0.000383 seconds
   🚀 NumPy is 67.4x FASTER!


## 2. Creating NumPy Arrays (10 minutes)

### 2.1 Different ways to create arrays

NumPy arrays are the core of the NumPy library. Think of them as enhanced lists that can perform mathematical operations efficiently.

In [ ]:
# Method 1: From Python lists
# 1D array (like a vector)
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)
print("Type:", type(arr1d))

# 2D array (like a matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)

# 3D array (like a cube of numbers)
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(arr3d)

In [ ]:
# Method 2: Using built-in functions

# Create array of zeros
zeros = np.zeros(5)  # 1D array of 5 zeros
print("Zeros:", zeros)

zeros_2d = np.zeros((3, 4))  # 3x4 matrix of zeros
print("\n2D Zeros:")
print(zeros_2d)

# Create array of ones
ones = np.ones((2, 3))
print("\nOnes:")
print(ones)

# Create array with a range of values
range_array = np.arange(0, 10, 2)  # Start=0, Stop=10, Step=2
print("\nRange array:", range_array)

# Create evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)  # 5 numbers between 0 and 1
print("Linspace array:", linspace_array)

### 2.3 Arrays vs Matrices: What's the Difference?

NumPy has both **arrays** and **matrices** - let's understand when to use each!

In [7]:
# 🔬 Arrays vs Matrices Comparison
print("🔍 ARRAYS vs MATRICES: The Ultimate Showdown!")
print("=" * 60)

# Create sample data
data = [[1, 2], [3, 4]]

# Method 1: NumPy Array (recommended)
numpy_array = np.array(data)
print("📊 NumPy Array:")
print(f"   Type: {type(numpy_array)}")
print(f"   Shape: {numpy_array.shape}")
print(f"   Data:\n{numpy_array}")
print()

# Method 2: NumPy Matrix (legacy - not recommended)
numpy_matrix = np.matrix(data)
print("🧮 NumPy Matrix:")
print(f"   Type: {type(numpy_matrix)}")
print(f"   Shape: {numpy_matrix.shape}")
print(f"   Data:\n{numpy_matrix}")
print()

print("⚔️ MULTIPLICATION BEHAVIOR - The Key Difference!")
print("-" * 60)

# Array multiplication (element-wise)
array_result = numpy_array * numpy_array
print("🔸 Array multiplication (element-wise):")
print(f"   array * array = \n{array_result}")
print()

# Matrix multiplication (linear algebra)
matrix_result = numpy_matrix * numpy_matrix
print("🔸 Matrix multiplication (linear algebra):")
print(f"   matrix * matrix = \n{matrix_result}")
print()

# To get matrix multiplication with arrays, use @ or np.dot()
array_matmul = numpy_array @ numpy_array  # or np.dot(numpy_array, numpy_array)
print("🔸 Array with matrix multiplication operator (@):")
print(f"   array @ array = \n{array_matmul}")
print()

print("🎯 COMPARISON TABLE")
print("-" * 60)

🔍 ARRAYS vs MATRICES: The Ultimate Showdown!
📊 NumPy Array:
   Type: <class 'numpy.ndarray'>
   Shape: (2, 2)
   Data:
[[1 2]
 [3 4]]

🧮 NumPy Matrix:
   Type: <class 'numpy.matrix'>
   Shape: (2, 2)
   Data:
[[1 2]
 [3 4]]

⚔️ MULTIPLICATION BEHAVIOR - The Key Difference!
------------------------------------------------------------
🔸 Array multiplication (element-wise):
   array * array = 
[[ 1  4]
 [ 9 16]]

🔸 Matrix multiplication (linear algebra):
   matrix * matrix = 
[[ 7 10]
 [15 22]]

🔸 Array with matrix multiplication operator (@):
   array @ array = 
[[ 7 10]
 [15 22]]

🎯 COMPARISON TABLE
------------------------------------------------------------


### 2.2 Array Properties

Every NumPy array has important properties that help us understand its structure:

In [8]:
# Let's explore array properties
sample_array = np.array([[1, 2, 3, 4], 
                        [5, 6, 7, 8], 
                        [9, 10, 11, 12]])

print("Sample Array:")
print(sample_array)
print()

# Shape: dimensions of the array
print(f"Shape: {sample_array.shape}")  # (rows, columns)

# Size: total number of elements
print(f"Size: {sample_array.size}")

# Number of dimensions
print(f"Dimensions (ndim): {sample_array.ndim}")

# Data type
print(f"Data type: {sample_array.dtype}")

# Memory usage (in bytes)
print(f"Memory usage: {sample_array.nbytes} bytes")

Sample Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Size: 12
Dimensions (ndim): 2
Data type: int64
Memory usage: 96 bytes


## 3. Array Indexing and Slicing (10 minutes)

### 3.1 Indexing: Accessing individual elements

Just like Python lists, but more powerful with multi-dimensional arrays!

In [9]:
# 1D Array indexing
arr_1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr_1d)

# Access single elements (0-indexed)
print(f"First element: {arr_1d[0]}")
print(f"Last element: {arr_1d[-1]}")
print(f"Third element: {arr_1d[2]}")

print("\n" + "="*50 + "\n")

# 2D Array indexing
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print("2D Array:")
print(arr_2d)

# Access elements: [row, column]
print(f"Element at row 0, column 1: {arr_2d[0, 1]}")
print(f"Element at row 2, column 0: {arr_2d[2, 0]}")

# Access entire rows or columns
print(f"First row: {arr_2d[0, :]}")      # All columns in row 0
print(f"Second column: {arr_2d[:, 1]}")  # All rows in column 1

1D Array: [10 20 30 40 50]
First element: 10
Last element: 50
Third element: 30


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, column 1: 2
Element at row 2, column 0: 7
First row: [1 2 3]
Second column: [2 5 8]


### 3.2 Slicing: Accessing multiple elements at once

Slicing allows us to extract portions of arrays efficiently.

In [10]:
# Slicing syntax: [start:stop:step]
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)

# Basic slicing
print(f"Elements 2 to 5: {arr[2:6]}")      # Index 2 to 5 (6 excluded)
print(f"First 5 elements: {arr[:5]}")      # From start to index 4
print(f"Last 3 elements: {arr[-3:]}")      # Last 3 elements
print(f"Every other element: {arr[::2]}")   # Every 2nd element

print("\n" + "="*50 + "\n")

# 2D Array slicing
matrix = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])
print("2D Array:")
print(matrix)

# Slice rows and columns
print("\nFirst 2 rows, first 3 columns:")
print(matrix[:2, :3])

print("\nLast 2 rows, last 2 columns:")
print(matrix[-2:, -2:])

Original array: [0 1 2 3 4 5 6 7 8 9]
Elements 2 to 5: [2 3 4 5]
First 5 elements: [0 1 2 3 4]
Last 3 elements: [7 8 9]
Every other element: [0 2 4 6 8]


2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First 2 rows, first 3 columns:
[[1 2 3]
 [5 6 7]]

Last 2 rows, last 2 columns:
[[ 7  8]
 [11 12]]


## 4. Mathematical Operations (15 minutes)

### 4.1 Element-wise operations

One of NumPy's superpowers: performing operations on entire arrays at once!

In [11]:
# Create sample arrays
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("Array a:", a)
print("Array b:", b)
print()

# Basic arithmetic operations (element-wise)
print("Addition (a + b):", a + b)
print("Subtraction (a - b):", a - b)
print("Multiplication (a * b):", a * b)
print("Division (a / b):", a / b)
print("Power (a ** 2):", a ** 2)

print("\n" + "="*50 + "\n")

# Operations with scalars (broadcasting)
print("Add 5 to all elements:", a + 5)
print("Multiply by 3:", a * 3)
print("Square root:", np.sqrt(a))

Array a: [1 2 3 4]
Array b: [10 20 30 40]

Addition (a + b): [11 22 33 44]
Subtraction (a - b): [ -9 -18 -27 -36]
Multiplication (a * b): [ 10  40  90 160]
Division (a / b): [0.1 0.1 0.1 0.1]
Power (a ** 2): [ 1  4  9 16]


Add 5 to all elements: [6 7 8 9]
Multiply by 3: [ 3  6  9 12]
Square root: [1.         1.41421356 1.73205081 2.        ]


### 4.2 Useful Mathematical Functions

In [ ]:
# Sample data for mathematical functions
data = np.array([1, 4, 9, 16, 25])
print("Data:", data)

# Statistical functions
print(f"Sum: {np.sum(data)}")
print(f"Mean: {np.mean(data)}")
print(f"Standard deviation: {np.std(data)}")
print(f"Minimum: {np.min(data)}")
print(f"Maximum: {np.max(data)}")

print("\n" + "="*30 + "\n")

# 2D array statistics
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("2D Matrix:")
print(matrix)

print(f"Sum of all elements: {np.sum(matrix)}")
print(f"Sum along rows (axis=0): {np.sum(matrix, axis=0)}")
print(f"Sum along columns (axis=1): {np.sum(matrix, axis=1)}")

print("\n" + "="*30 + "\n")

# Trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Angles (in radians):", angles)
print("Sine values:", np.sin(angles))
print("Cosine values:", np.cos(angles))

### 4.3 Advanced Array Operations: Axis, Transpose & Broadcasting

Understanding these concepts will make you a NumPy power user!

#### A. Understanding Axis Operations

Think of **axis** as the direction along which an operation is performed:
- **axis=0**: Operations along rows (↓ direction)
- **axis=1**: Operations along columns (→ direction)

In [ ]:
# Create a 3x4 matrix for demonstration
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])

print("Original Matrix (3x4):")
print(matrix)
print(f"Shape: {matrix.shape}")
print()

# Operations along different axes
print("=== AXIS OPERATIONS ===")
print(f"Sum all elements: {np.sum(matrix)}")
print(f"Sum along axis=0 (↓, collapse rows): {np.sum(matrix, axis=0)}")
print(f"Sum along axis=1 (→, collapse cols): {np.sum(matrix, axis=1)}")
print()

print("Mean operations:")
print(f"Mean along axis=0: {np.mean(matrix, axis=0)}")
print(f"Mean along axis=1: {np.mean(matrix, axis=1)}")
print()

print("Max operations:")
print(f"Max along axis=0: {np.max(matrix, axis=0)}")
print(f"Max along axis=1: {np.max(matrix, axis=1)}")
print()

# Keep dimensions with keepdims
print("=== KEEPING DIMENSIONS ===")
sum_keepdims = np.sum(matrix, axis=1, keepdims=True)
print(f"Sum axis=1 with keepdims: \n{sum_keepdims}")
print(f"Shape with keepdims: {sum_keepdims.shape}")  # (3,1) instead of (3,)

#### B. Transpose Operations

**Transpose** flips the matrix along its diagonal - rows become columns and vice versa.

In [ ]:
# Original matrix (3x4)
original = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8], 
                     [9, 10, 11, 12]])

print("Original Matrix (3x4):")
print(original)
print(f"Shape: {original.shape}")
print()

# Three ways to transpose
print("=== TRANSPOSE METHODS ===")

# Method 1: .T attribute
transposed1 = original.T
print("Method 1 - .T attribute:")
print(transposed1)
print(f"New shape: {transposed1.shape}")
print()

# Method 2: .transpose() method
transposed2 = original.transpose()
print("Method 2 - .transpose():")
print(transposed2)
print()

# Method 3: np.transpose() function
transposed3 = np.transpose(original)
print("Method 3 - np.transpose():")
print(transposed3)
print()

# Practical example: Matrix multiplication setup
print("=== PRACTICAL EXAMPLE ===")
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("A × B:")
print(np.dot(A, B))
print("A × B^T (B transposed):")
print(np.dot(A, B.T))

#### C. Broadcasting: NumPy's Superpower

**Broadcasting** allows NumPy to perform operations on arrays with different shapes. It's like NumPy automatically "stretches" smaller arrays to match larger ones.

In [2]:
# Broadcasting examples
print("=== BROADCASTING EXAMPLES ===")

# Example 1: Array + Scalar
arr = np.array([1, 2, 3, 4])
print("Array:", arr)
print("Array + 10:", arr + 10)  # Scalar 10 is "broadcast" to all elements
print()

# Example 2: 2D Array + 1D Array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_vector = np.array([10, 20, 30])

print("Matrix (3x3):")
print(matrix)
print("Row vector (3,):", row_vector)
print("Matrix + Row vector:")
print(matrix + row_vector)  # Row vector added to each row
print()

# Example 3: Column vector broadcasting
col_vector = np.array([[100], 
                       [200], 
                       [300]])  # Shape: (3,1)

print("Column vector (3x1):")
print(col_vector)
print("Matrix + Column vector:")
print(matrix + col_vector)  # Column vector added to each column
print()

# Example 4: Real-world example - Normalizing data
print("=== PRACTICAL BROADCASTING ===")
data = np.array([[85, 90, 78],
                 [92, 88, 95],
                 [75, 85, 82]])

print("Student grades:")
print(data)

# Calculate mean for each subject (column-wise)
subject_means = np.mean(data, axis=0)
print("Subject means:", subject_means)

# Normalize: subtract mean from each column (broadcasting!)
normalized = data - subject_means
print("Normalized grades (centered around 0):")
print(normalized)

# Calculate standard deviation and standardize
subject_stds = np.std(data, axis=0)
standardized = (data - subject_means) / subject_stds
print("Standardized grades (mean=0, std=1):")
print(standardized)

=== BROADCASTING EXAMPLES ===
Array: [1 2 3 4]
Array + 10: [11 12 13 14]

Matrix (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row vector (3,): [10 20 30]
Matrix + Row vector:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Column vector (3x1):
[[100]
 [200]
 [300]]
Matrix + Column vector:
[[101 102 103]
 [204 205 206]
 [307 308 309]]

=== PRACTICAL BROADCASTING ===
Student grades:
[[85 90 78]
 [92 88 95]
 [75 85 82]]
Subject means: [84.         87.66666667 85.        ]
Normalized grades (centered around 0):
[[ 1.          2.33333333 -7.        ]
 [ 8.          0.33333333 10.        ]
 [-9.         -2.66666667 -3.        ]]
Standardized grades (mean=0, std=1):
[[ 0.14334554  1.13554995 -0.96456195]
 [ 1.14676436  0.16222142  1.37794564]
 [-1.2901099  -1.29777137 -0.41338369]]


#### Broadcasting Rules (Important!)

NumPy broadcasting follows these rules:
1. **Start from the trailing dimension** and work backwards
2. **Dimensions are compatible** if:
   - They are equal, OR
   - One of them is 1, OR  
   - One of them doesn't exist (missing dimension)
3. **Missing dimensions** are assumed to be 1

**Examples:**
- `(3, 4) + (4,)` ✅ Works: `(3, 4) + (1, 4)`
- `(3, 4) + (3, 1)` ✅ Works  
- `(3, 4) + (2, 4)` ❌ Fails: 3 ≠ 2

## 5. Practical Examples (10 minutes)

Let's apply what we've learned to solve real-world problems!

### Example 1: Student Grade Analysis

In [ ]:
# Student grades in 3 subjects: [Math, Science, English]
# Each row represents one student
student_grades = np.array([
    [85, 92, 78],  # Student 1
    [90, 88, 95],  # Student 2  
    [75, 85, 82],  # Student 3
    [95, 90, 88],  # Student 4
    [88, 87, 91]   # Student 5
])

print("Student Grades (Math, Science, English):")
print(student_grades)
print()

# Calculate average grade for each student
student_averages = np.mean(student_grades, axis=1)
print("Average grade per student:", student_averages)

# Calculate average grade for each subject
subject_averages = np.mean(student_grades, axis=0)
print("Average grade per subject:", subject_averages)

# Find the best student (highest average)
best_student = np.argmax(student_averages)
print(f"Best performing student: Student {best_student + 1} with average {student_averages[best_student]:.2f}")

# Find students who scored above 85 in all subjects
all_above_85 = np.all(student_grades >= 85, axis=1)
print(f"Students with all grades ≥ 85: {np.where(all_above_85)[0] + 1}")

### Example 2: Temperature Data Analysis

In [ ]:
# Temperature data for a week (in Celsius)
temperatures = np.array([22, 25, 28, 30, 27, 24, 21])
days = np.array(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])

print("Daily temperatures:", temperatures)
print("Days:", days)
print()

# Convert Celsius to Fahrenheit: F = C * 9/5 + 32
temperatures_f = temperatures * 9/5 + 32
print("Temperatures in Fahrenheit:", temperatures_f)

# Find statistics
print(f"Average temperature: {np.mean(temperatures):.2f}°C")
print(f"Highest temperature: {np.max(temperatures)}°C on {days[np.argmax(temperatures)]}")
print(f"Lowest temperature: {np.min(temperatures)}°C on {days[np.argmin(temperatures)]}")

# Find days with temperature above average
above_average = temperatures > np.mean(temperatures)
print(f"Days above average: {days[above_average]}")

## Bonus: Quick Reference Sheet

### Essential NumPy Functions:

```python
# Array Creation
np.array([1, 2, 3])          # From list
np.zeros((3, 4))             # Array of zeros
np.ones((2, 3))              # Array of ones
np.arange(0, 10, 2)          # Range array
np.linspace(0, 1, 5)         # Evenly spaced

# Array Properties  
arr.shape                    # Dimensions
arr.size                     # Total elements
arr.dtype                    # Data type
arr.ndim                     # Number of dimensions

# Indexing & Slicing
arr[0]                       # First element
arr[-1]                      # Last element
arr[1:4]                     # Slice
arr[:, 1]                    # Column slice (2D)

# Mathematical Operations
np.sum(arr)                  # Sum all elements
np.mean(arr)                 # Average
np.std(arr)                  # Standard deviation
np.min(arr), np.max(arr)     # Min and max
np.sqrt(arr)                 # Square root
```

---

**Happy NumPy coding! 🐍📊**